# Generated by Django 5.2.16 on 2026-09-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_subscription_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brokerage_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
