# Generated by Django 5.2.16 on 2026-09-22 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stratas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bylaw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('standard_fine', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('strata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bylaws', to='stratas.strataplan')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('strata', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_type', models.CharField(choices=[('BYLAW', 'Bylaw Infraction'), ('DEFICIENCY', 'Common Property Deficiency')], default='BYLAW', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('unit_number', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='incidents/evidence/')),
                ('status', models.CharField(choices=[('LOGGED', 'Draft/Newly submitted'), ('PENDING_MANAGER', 'Awaiting manager review'), ('NOTICE_ISSUED', 'Formal notice sent, statutory clock running'), ('RESPONSE_RECEIVED', 'Owner submitted written statement'), ('HEARING_REQUESTED', 'Owner requested in-person council hearing'), ('VOTING_OPEN', 'Ready for digital council ballot'), ('RESOLVED_FINED', 'Fine authorized and posted'), ('RESOLVED_DISMISSED', 'Dismissed or warning issued')], default='LOGGED', max_length=20)),
                ('notice_issued_at', models.DateTimeField(blank=True, null=True)),
                ('statutory_deadline', models.DateTimeField(blank=True, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('manager_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bylaw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='dockets.bylaw')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_incidents', to=settings.AUTH_USER_MODEL)),
                ('strata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='stratas.strataplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('WRITTEN', 'Submit Written Explanation'), ('HEARING', 'Request In-Person Hearing')], max_length=20)),
                ('statement', models.TextField(blank=True)),
                ('counter_evidence', models.FileField(blank=True, null=True, upload_to='incidents/responses/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='dockets.incident')),
            ],
        ),
        migrations.CreateModel(
            name='CouncilVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_fine', models.BooleanField(help_text='True = levy fine, False = dismiss/warn')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_votes', to='stratas.membership')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='dockets.incident')),
            ],
            options={
                'unique_together': {('incident', 'member')},
            },
        ),
    ]
