# Generated by Django 5.2.16 on 2026-09-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bylaw',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
