# Generated by Django 5.2.16 on 2026-09-30 22:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockets', '0003_bylaw_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='strata_lot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('IN_REVIEW', 'Awaiting Manager Review'), ('NOTICE_ISSUED', 'Statutory Notice Issued'), ('RESPONSE_RECEIVED', 'Response Received'), ('VOTING_OPEN', 'Council Ballot Open'), ('RESOLVED_FINED', 'Fine Authorized'), ('RESOLVED_DISMISSED', 'Closed / Dismissed')], default='IN_REVIEW', max_length=20),
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('RECURRENCE', 'Subsequent Occurrence'), ('EVIDENCE', 'Additional Evidence'), ('NOTE', 'Manager / Council Note'), ('UNIT_CORRECTED', 'Unit Corrected'), ('STATUTORY_NOTICE', 'S.135 Notice Dispatched')], max_length=30)),
                ('description', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='incidents/evidence_events/')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dockets.incident')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
    ]
