# Generated by Django 5.2.16 on 2026-10-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockets', '0004_incident_strata_lot_alter_incident_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentevent',
            name='event_type',
            field=models.CharField(choices=[('RECURRENCE', 'Subsequent Occurrence'), ('EVIDENCE', 'Additional Evidence'), ('NOTE', 'Manager / Council Note'), ('UNIT_CORRECTED', 'Unit Corrected'), ('STATUTORY_NOTICE', 'S.135 Notice Dispatched'), ('OWNER_STATEMENT', 'Owner Written Response'), ('HEARING_REQUESTED', 'Council Hearing Requested')], max_length=30),
        ),
    ]
