# Generated by Django 5.2.16 on 2026-10-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockets', '0005_alter_incidentevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentevent',
            name='event_type',
            field=models.CharField(choices=[('RECURRENCE', 'Subsequent Occurrence'), ('EVIDENCE', 'Additional Evidence'), ('NOTE', 'Manager / Council Note'), ('UNIT_CORRECTED', 'Unit Corrected'), ('STATUTORY_NOTICE', 'S.135 Notice Dispatched'), ('OWNER_STATEMENT', 'Owner Written Response'), ('HEARING_REQUESTED', 'Council Hearing Requested'), ('FINE_DISPATCHED', 'Official Fine Dispatched')], max_length=30),
        ),
        migrations.DeleteModel(
            name='IncidentResponse',
        ),
    ]
