# Generated by Django 5.2.16 on 2026-09-21 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrataPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_number', models.CharField(db_index=True, help_text='Official plan identifier registered with the land authority (e.g. EPS 412)', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Building or complex trade name (e.g. Kingsview Manor)', max_length=150)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(default='BC', help_text='e.g. BC, ON, WA, FL', max_length=50)),
                ('postal_code', models.CharField(help_text='Postal Code or ZIP', max_length=20)),
                ('country', models.CharField(default='CA', help_text='ISO 2-letter country code (CA, US)', max_length=2)),
                ('total_units', models.PositiveIntegerField(default=1, help_text='Total number of registered strata lots')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stratas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strata Plan',
                'verbose_name_plural': 'Strata Plans',
                'ordering': ['plan_number'],
            },
        ),
        migrations.CreateModel(
            name='StrataInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('PRESIDENT', 'Council President / Chair'), ('COUNCIL', 'Council Member'), ('MANAGER', 'Licensed Strata Manager'), ('CARETAKER', 'Building Caretaker / Staff')], max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('strata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='stratas.strataplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('PRESIDENT', 'Council President / Chair'), ('COUNCIL', 'Council Member'), ('MANAGER', 'Licensed Strata Manager'), ('CARETAKER', 'Building Caretaker / Staff')], default='COUNCIL', max_length=20)),
                ('unit_number', models.CharField(blank=True, help_text='Unit / Lot number owned or occupied', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('strata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='stratas.strataplan')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'strata', 'is_active'], name='stratas_mem_user_id_65b4cd_idx')],
                'unique_together': {('user', 'strata')},
            },
        ),
    ]
